# Generated by Django 4.1.2 on 2024-06-04 13:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0046_alter_commonmaster_value_for'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customsession',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='customsession',
            name='session_ptr',
        ),
        migrations.AddField(
            model_name='customsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customsession',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
