# Generated by Django 4.1.2 on 2024-06-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0047_alter_customsession_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsession',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
